modified Gateway RPC Proxy methods
The-APIS/apis-core pull request #53
Opened 2021-06-01 12:53 UTC by AjmalAhamedKodakkat

Modified Gateway RPC proxy methods

2021-06-01 22:40 UTC, srslafazan commented on gateway/src/constructors/express/routes/api/v1/rpc/index.js
> +  router.use('/binance-smart-chain', require('./chainHandler')(context))
`rpcHandler` would be a more clear name

2021-06-01 22:41 UTC, srslafazan commented on gateway/src/constructors/express/routes/api/v1/rpc/chainHandler.js
> +const chainHandler = module.exports = ({ }) => {
Perhaps this should be `rpcHandler`, since it handles chain and network

2021-06-01 22:41 UTC, srslafazan commented on gateway/src/constructors/express/routes/api/v1/rpc/chainHandler.js
> +      else if (urlValue === 'binance-smart-chain' || 'bsc') {
`urlValue === 'binance-smart-chain' || urlValue === 'bsc'`

or `['binance-smart-chain', 'bsc].includes(urlValue)`

2021-06-01 22:50 UTC, srslafazan commented on gateway/src/constructors/express/routes/api/v1/rpc/chainHandler.js
> +    try {
We can reduce the size of this implementation even further with a map:

```javascript
const RPC_HANDLER_DEFAULTS = {
  ethereum: {
    defaults: {
      chain: 'ethereum',
      network: 'rinkeby',
  },
  bitcoin: {
    defaults: {
      chain: 'bitcoin',
      network: 'testnet',
  },
  binance_smart_chain: {
    defaults: {
      chain: 'binance_smart_chain',
      network: 'testnet',
  },
}

const rpcHandler = module.exports = ({}) => {

// ...

const defaults = get(RPC_HANDLER_DEFAULTS, [urlValue, 'defaults') 

const { data, status } = await axios.post(`${getRPCServiceAddress({
  chain: defaults.chain,
  network: req.query.network || defaults.network,
})}/api/v1/rpc`, req.body)
```

2021-06-01 22:56 UTC, srslafazan commented on gateway/src/constructors/express/routes/api/v1/rpc/chainHandler.js
> +      else if (urlValue === 'binance-smart-chain' || 'bsc') {
not necessary if we use the above logic

2021-06-01 22:56 UTC, srslafazan requested changes
Looking good! Minor changes are necessary and we could significantly reduce logic with a map.

2021-06-02 10:46 UTC, AjmalAhamedKodakkat commented
Revised based on the review.

2021-06-02 10:46 UTC, closed without merging